"""Generate lean/Sanskrit/Lexicon.lean from the selection TSVs.

The Lean lexicon is a build artifact of this pipeline: selection lists come
from DCS corpus frequencies (see select_lexicon.py), and this script renders
them as Lean definitions. Do not edit Lexicon.lean by hand — rerun this.
"""

import csv
import json
from pathlib import Path

DIGRAPHS = [("ai", "E"), ("au", "O"), ("kh", "K"), ("gh", "G"), ("ch", "C"),
            ("jh", "J"), ("ṭh", "W"), ("ḍh", "Q"), ("th", "T"), ("dh", "D"),
            ("ph", "P"), ("bh", "B")]
SINGLE = {"ā": "A", "ī": "I", "ū": "U", "ṛ": "f", "ṝ": "F", "ḷ": "x",
          "ṃ": "M", "ḥ": "H", "ṅ": "N", "ñ": "Y", "ṭ": "w", "ḍ": "q",
          "ṇ": "R", "ś": "S", "ṣ": "z"}

def slp1_lemma(iast: str) -> str:
    out, i = [], 0
    while i < len(iast):
        for d, r in DIGRAPHS:
            if iast.startswith(d, i):
                out.append(r); i += len(d); break
        else:
            out.append(SINGLE.get(iast[i], iast[i])); i += 1
    return "".join(out)

here = Path(__file__).parent
out = here.parent.parent / "lean" / "Sanskrit" / "Lexicon.lean"

nouns = list(csv.DictReader(open(here / "selection" / "selection_nouns.tsv", encoding="utf-8"), delimiter="\t"))
adjs = list(csv.DictReader(open(here / "selection" / "selection_adjs.tsv", encoding="utf-8"), delimiter="\t"))
verbs = list(csv.DictReader(open(here / "selection" / "selection_verbs.tsv", encoding="utf-8"), delimiter="\t"))

ADJ_CLS = {"a_adj": ".a", "a_pron": ".pron", "a_pron_at": ".pron_at",
           "a_pron_opt": ".pron_opt", "i_adj": ".i", "u_adj": ".u",
           "in_adj": ".inn", "mat_adj": ".mat", "mahat": ".mat"}

INDECLINABLES = [
    ("ca", "and"), ("vA", "or"), ("tu", "but"), ("na", "not"), ("iti", "thus"),
    ("api", "also"), ("eva", "indeed"), ("hi", "for"), ("Kalu", "indeed"),
    ("kila", "indeed"), ("nu", "now"), ("atra", "here"), ("tatra", "there"),
    ("iha", "here"), ("adya", "today"), ("tadA", "then"), ("sadA", "always"),
    ("nityam", "always"), ("tataH", "then"), ("aTa", "now"), ("punaH", "again"),
    ("taTA", "thus"), ("evam", "thus"), ("saha", "with"),
]

def esc(s: str) -> str:
    return s.replace("\\", "").replace('"', "'")

PERSON = {"3": ".third", "2": ".second", "1": ".first"}
NUMBER = {"Sing": ".sg", "Dual": ".du", "Plur": ".pl"}

lines = []
w = lines.append
w("import Sanskrit.Nouns")
w("import Sanskrit.Verbs")
w("")
w("/-!")
w("# Lexicon (GENERATED — do not edit)")
w("")
w("Generated by data/dcs/generate_lexicon.py from the Digital Corpus of")
w("Sanskrit (DCS, Hellwig): the top lemmas by fragment-usable corpus")
w("frequency — declined non-compound tokens for nominals, finite present")
w("indicative (non-passive) tokens for verbs. Athematic verb paradigms are")
w("curated tables validated against attested corpus cells; transitivity is")
w(f"estimated from accusative co-occurrence. {len(nouns)} nouns, "
  f"{len(adjs)} adjectives, {len(set(v['lemma'] for v in verbs))} verbs, "
  f"{len(INDECLINABLES)} indeclinables.")
w("-/")
w("")
w("namespace Sanskrit")
w("")
w("structure NounEntry where")
w("  stem  : String")
w("  cls   : StemClass")
w("  gloss : String")
w("  pada  : String := \"\"   -- word-final base of a root stem (vāc → vāk)")
w("  deriving Repr")
w("")
w("inductive AdjClass")
w("  | a         -- sundara: a-stem masc/neut, ā- or ī-feminine")
w("  | pron      -- sarva: pronominal, neuter -am")
w("  | pron_at   -- anya: pronominal, neuter -at")
w("  | pron_opt  -- pūrva: pronominal and plain endings both classical")
w("  | i | u     -- śuci, bahu")
w("  | inn       -- balin, yogin-type")
w("  | mat       -- bhagavat, mahat")
w("  deriving DecidableEq, Repr")
w("")
w("structure AdjEntry where")
w("  stem    : String")
w("  cls     : AdjClass")
w("  femStem : String")
w("  gloss   : String")
w("  deriving Repr")
w("")
w("structure VerbEntry where")
w("  lemma : String")
w("  stem  : String            -- thematic present stem; \"\" for athematic")
w("  pada  : Pada")
w("  trans : Bool              -- requires an accusative object")
w("  gloss : String")
w("  forms : AthematicTable := []")
w("  deriving Repr")
w("")
w("/-- The three (stem, class) paradigms an adjective declines in. -/")
w("def AdjEntry.triples (e : AdjEntry) : List (String × StemClass) :=")
w("  let femCls : StemClass :=")
w("    if e.femStem.back == 'I' then .I_f")
w("    else if e.femStem.back == 'A' then .A_f")
w("    else if e.femStem.back == 'i' then .i_f else .u_f")
w("  match e.cls with")
w("  | .a        => [(e.stem, .a_m), (e.stem, .a_n), (e.femStem, femCls)]")
w("  | .pron     => [(e.stem, .pron_m), (e.stem, .pron_n), (e.femStem, .pron_f)]")
w("  | .pron_at  => [(e.stem, .pron_m), (e.stem, .pron_n_at), (e.femStem, .pron_f)]")
w("  | .pron_opt => [(e.stem, .pron_opt_m), (e.stem, .pron_opt_n), (e.femStem, .pron_opt_f)]")
w("  | .i        => [(e.stem, .i_m), (e.stem, .i_n), (e.femStem, femCls)]")
w("  | .u        => [(e.stem, .u_m), (e.stem, .u_n), (e.femStem, femCls)]")
w("  | .inn      => [(e.stem, .in_m), (e.stem, .in_n), (e.femStem, .I_f)]")
w("  | .mat      => [(e.stem, .mat_m), (e.stem, .mat_n), (e.femStem, .I_f)]")
w("")
w("/-- All present forms of a verb entry (a thematic form, or a table cell). -/")
w("def VerbEntry.presentForms (e : VerbEntry) (p : Person) (n : Number) : List String :=")
w("  if e.forms.isEmpty then [conjugate e.stem e.pada p n]")
w("  else match athematicForm e.forms p n with")
w("       | some f => [f]")
w("       | none => []")
w("")
w("private def N (stem : String) (cls : StemClass) (gloss : String)")
w("    (pada : String := \"\") : NounEntry :=")
w("  ⟨stem, cls, gloss, pada⟩")
w("")
w("def nouns : List NounEntry := [")
noun_lines = []
for r in nouns:
    cls = r["class"]
    if cls.startswith("cons_"):
        c, pada = cls.split(":")
        noun_lines.append(f'  N "{r["slp1"]}" .{c} "{esc(r["gloss"])}" "{pada}"')
    else:
        noun_lines.append(f'  N "{r["slp1"]}" .{cls} "{esc(r["gloss"])}"')
w(",\n".join(noun_lines) + "]")
w("")
w("def adjectives : List AdjEntry := [")
adj_lines = []
for r in adjs:
    fem = r["fem_slp1"] or (r["slp1"] + "I")  # mahat -> mahatI
    adj_lines.append(f'  ⟨"{r["slp1"]}", {ADJ_CLS[r["class"]]}, "{fem}", "{esc(r["gloss"])}"⟩')
w(",\n".join(adj_lines) + "]")
w("")
w("def verbs : List VerbEntry := [")
verb_lines = []
for r in verbs:
    lemma_slp = r["slp1_stem"]
    pada = f'.{r["pada"]}'
    trans = "true" if r["trans"] == "1" else "false"
    gloss = esc(r["gloss"])
    if r["kind"] == "athem":
        table = json.loads(r["slp1_stem"][len("ATHEM:"):])
        # lemma must be transliterated separately for athematic rows
        cells = ", ".join(
            f'({PERSON[c.split("|")[0]]}, {NUMBER[c.split("|")[1]]}, "{f}")'
            for c, f in table.items())
        verb_lines.append(f'  ⟨"{slp1_lemma(r["lemma"])}", "", {pada}, {trans}, "{gloss}",\n    [{cells}]⟩')
    else:
        verb_lines.append(f'  ⟨"{slp1_lemma(r["lemma"])}", "{lemma_slp}", {pada}, {trans}, "{gloss}", []⟩')

w(",\n".join(verb_lines) + "]")
w("")
w("def indeclinables : List (String × String) := [")
w(",\n".join(f'  ("{f}", "{g}")' for f, g in INDECLINABLES) + "]")
w("")
w("end Sanskrit")

out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {out} ({len(lines)} lines)")
